### ISSUE TITLE
Absolute File Path for `~/.brownie/`

### ISSUE THREAD

**Issue by atnjqt** [PatrickAlphaC/chainlink-mix#1]
In the build contract for **PriceFeed.json** example, there is an absolute path which references your local home directory, @PatrickAlphaC 

https://github.com/PatrickAlphaC/chainlink-mix/blob/806d57638367254af992de87aef88a5d765ce3b3/build/contracts/PriceFeed.json#L54

**Comment by atnjqt** [comment]
Maybe not an issue necessarily, but I found this while trying to follow along with [https://blog.chain.link/develop-python-defi-project/](https://blog.chain.link/develop-python-defi-project/) ...

**Comment by PatrickAlphaC** [comment]
Ah thanks! I'll have to delete the build folder. It shouldn't be in the repo.

**Comment by PatrickAlphaC** [comment]
I'm closing this in favor of the new home: https://github.com/smartcontractkit/chainlink-mix
